spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      #      ddl-auto: update
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
jwt:
  expiration: ${JWT_EXPIRATION:900000}
  key: ${JWT_KEY:Qhdm=-zbkh-UfJR7d2WPttaa7ugf$C3smjQ4u#HEBoSRwrJT4yMgWJYqVn9U5SDqNTPeQzSnsqv=nEfR3q2LKaghFtWWVeK3yQ4wgNLzMxpTGIbxHi6Ptb1-!R5VVugxxUZniVUDg&pG=XqSr8k4dvMMOHWAp$Lo8V5uzB3ob8Ozm3WO6dlh5AT25uII7ZjXv8JGnCJLze3MCGeDIdfTGWjlA=Nee3DNhp38d96H7N#Cl3_Tx7I5EL6f3ID#K=qS7msQO4fDD=8F5-lvV5M-Vp0KIFRW!B=amx$a_6=X_pt9KsJhJw52m3!m$pkp_B4gkl3yZX9QWbgOKX9E6HLgoPo5}
